# №2 Дәріс: Python-да NumPy кітапханасымен векторлық есептеулер

**NumPy** (Numerical Python) - бұл Python-дағы ғылыми және инженерлік есептеулерге арналған негізгі кітапхана. Ол Pandas, Scikit-learn, SciPy және басқа да көптеген деректерді талдау және машиналық оқыту құралдарының негізі болып табылады.

### Неліктен стандартты Python тізімдері емес, NumPy?

1.  **Жылдамдық:** NumPy ядросы C тілінде жазылған, бұл массивтермен операцияларды Python-ның әр қадамда интерпретацияны қажет ететін кәдімгі тізімдеріне қарағанда әлдеқайда жылдам етеді.
2.  **Жад тиімділігі:** NumPy массивтері (`ndarray`) бір типті деректерді сақтайды және әртүрлі типтегі нысандарға сілтемелерді сақтайтын тізімдерге қарағанда жадта айтарлықтай аз орын алады.
3.  **Ыңғайлылық:** NumPy сызықтық алгебра, кездейсоқ сандарды генерациялау, статистикалық операциялар және тағы басқалар үшін көптеген кіріктірілген функцияларды ұсынады.

**Біздің дәрістің мақсаттары:**
*   NumPy-дың негізгі нысаны — `ndarray`-мен танысу.
*   Әртүрлі тәсілдермен массивтерді құруды үйрену.
*   Массивтерді индекстеуді, кесінділерді (slicing) және пішінін өзгертуді меңгеру.
*   Векторлық математикалық операцияларды және хабар тарату (broadcasting) механизмін зерттеу.
*   NumPy-дың машиналық оқыту контекстінде қалай қолданылатынын түсіну.

### Кітапхананы импорттау

Жалпы қабылданған келісім бойынша, NumPy `np` бүркеншік атымен импортталады.

In [ ]:
import numpy as np

## 1. NumPy массивтерін құру

Массив құрудың көптеген тәсілдері бар. Ең танымалдарына тоқталайық.

### 1.1. Python тізімдерінен
Ең қарапайым тәсіл — `np.array()` функциясына тізімді немесе кірістірілген тізімдерді беру.

**Қолданылатын функциялар:**
*   `np.array()`: Кіріс деректерін (мысалы, тізім) `ndarray` массивіне айналдырады.

In [ ]:
my_list = [1, 2, 3, 4, 5]
arr_1d = np.array(my_list)
print("Бірөлшемді массив:\n", arr_1d)

my_nested_list = [[1, 2, 3], [4, 5, 6]]
arr_2d = np.array(my_nested_list)
print("\nЕкіөлшемді массив (матрица):\n", arr_2d)

Бірөлшемді массив:
[1 2 3 4 5]
Екіөлшемді массив (матрица):
[[1 2 3]
 [4 5 6]]


### 1.2. Кіріктірілген функциялар арқылы генерациялау
NumPy алдымен Python тізімін жасауды қажет етпей, массивтерді жылдам генерациялауға арналған функцияларды ұсынады.

**Қолданылатын функциялар:**
*   `np.arange(start, stop, step)`: Берілген аралықта белгілі бір қадаммен сандар массивін жасайды. Python-ның `range()` функциясының аналогы, бірақ қалқымалы нүктелі сандармен де жұмыс істей алады.
*   `np.linspace(start, stop, num)`: `[start, stop]` аралығында біркелкі орналасқан `num` саннан тұратын массив жасайды. Маңыздысы, `stop` мәні аралыққа кіреді.

In [ ]:
print(f"0-ден 9-ға дейінгі массив: {np.arange(10)}")
print(f"5-тен 15-ке дейін 2 қадаммен массив: {np.arange(5, 16, 2)}")

0-ден 9-ға дейінгі массив: [0 1 2 3 4 5 6 7 8 9]
5-тен 15-ке дейін 2 қадаммен массив: [ 5  7  9 11 13 15]


In [ ]:
print(f"0-ден 5-ке дейінгі 10 саннан тұратын массив: {np.linspace(0, 5, 10)}")

0-ден 5-ке дейінгі 10 саннан тұратын массив: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


Стандартты матрицаларды (нөлдік, бірлік) құру үшін арнайы функциялар бар.

**Қолданылатын функциялар:**
*   `np.zeros()`: Нөлдермен толтырылған массив жасайды.
*   `np.ones()`: Бірліктермен толтырылған массив жасайды.
*   `np.eye()`: Бірлік матрицасын (identity matrix) жасайды.

In [ ]:
# Нөлдермен толтырылған матрица. Пішіні кортеж (tuple) түрінде беріледі
print(f"Нөлдерден тұратын 3x4 матрицасы:\n{np.zeros((3, 4))}")

Нөлдерден тұратын 3x4 матрицасы:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Бірліктермен толтырылған матрица
print(f"Бірліктерден тұратын 2x3 матрицасы:\n{np.ones((2, 3))}")

Бірліктерден тұратын 2x3 матрицасы:
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Бірлік матрица (бас диагональда бірліктер, қалғандары нөлдер)
print(f"4x4 бірлік матрицасы:\n{np.eye(4)}")

4x4 бірлік матрицасы:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 1.3. Кездейсоқ деректерді генерациялау

`np.random` модулі — деректерді жасауға арналған таптырмас құрал. Біз "кездейсоқ" нәтижелеріміздің қайталануы үшін `seed` мәнін бекітеміз, бұл кодты жөндеу үшін маңызды.

**Қолданылатын функциялар:**
*   `np.random.seed()`: Кездейсоқ сандар генераторын инициализациялайды.
*   `np.random.rand()`: [0, 1) аралығындағы біркелкі үлестірілген сандарды генерациялайды.
*   `np.random.randn()`: Математикалық күтімі 0 және стандартты ауытқуы 1 болатын стандартты қалыпты (Гаусс) үлестірімінен сандарды генерациялайды.
*   `np.random.randint()`: Берілген аралықта кездейсоқ бүтін сандарды генерациялайды.

In [ ]:
np.random.seed(42) # Нәтижелердің қайталануы үшін seed-ті бекітеміз

In [ ]:
print(f"[0, 1) аралығындағы біркелкі үлестірілген 3x3 матрицасы:\n{np.random.rand(3,3)}")

[0, 1) аралығындағы біркелкі үлестірілген 3x3 матрицасы:
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [ ]:
print(f"Стандартты қалыпты үлестірілген 2x4 матрицасы:\n{np.random.randn(2,4)}")

Стандартты қалыпты үлестірілген 2x4 матрицасы:
[[ 0.70807258  0.02058449  0.96990985 -0.2021133 ]
 [-0.34791215  0.15634897  1.23029068  1.20237985]]


In [ ]:
print(f"10-нан 50-ге дейінгі кездейсоқ бүтін сандардан тұратын 4x5 матрицасы:\n{np.random.randint(10, 50, size=(4,5))}")

10-нан 50-ге дейінгі кездейсоқ бүтін сандардан тұратын 4x5 матрицасы:
[[14 33 28 23 20]
 [49 24 19 14 34]
 [22 24 20 20 42]
 [30 31 10 39 12]]


## 2. Атрибуттар, индекстеу және пішінді өзгерту

### 2.1. Массив атрибуттары
Әрбір NumPy массивінің оның құрылымын сипаттайтын маңызды атрибуттары бар.

**Қолданылатын атрибуттар:**
*   `.shape`: Әрбір осі (өлшемі) бойынша массивтің өлшемін сипаттайтын кортеж.
*   `.ndim`: Массивтің осьтерінің (өлшемдерінің) саны, бүтін сан.
*   `.dtype`: Массивте сақталған элементтердің деректер типі.

In [ ]:
arr = np.arange(10).reshape(2, 5)

print(f"Пішіні (shape): {arr.shape}")
print(f"Өлшемдер саны (ndim): {arr.ndim}")
print(f"Деректер типі (dtype): {arr.dtype}")

# NumPy массиві үшін `len()` бірінші осі бойынша өлшемді қайтарады
print(f"Ұзындығы (len): {len(arr)}")

Пішіні (shape): (2, 5)
Өлшемдер саны (ndim): 2
Деректер типі (dtype): int64
Ұзындығы (len): 2


### 2.2. Индекстеу және кесінділер (Slicing)
Бұл NumPy-дың ең қуатты құралдарының бірі. Массивтің элементтеріне және бөліктеріне икемді қол жеткізуге мүмкіндік береді.

In [ ]:
matrix = np.arange(1, 13).reshape(3, 4)
print(f"Матрица:\n{matrix}")

Матрица:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Бір элементті алу [жол, баған]
print(f"1-жол, 2-бағандағы элемент: {matrix[1, 2]}")

1-жол, 2-бағандағы элемент: 7


In [ ]:
# Бүкіл жолды алу
print(f"0-ші жолдың барлығы: {matrix[0, :]}") # : 'осы ось бойынша барлық элементтер' дегенді білдіреді

0-ші жолдың барлығы: [1 2 3 4]


In [ ]:
# Бүкіл бағанды алу
print(f"1-ші бағанның барлығы: {matrix[:, 1]}")

1-ші бағанның барлығы: [ 2  6 10]


In [ ]:
# Ішкі матрицаны алу
# 1-ден 2-ге дейінгі жолдар (қоса алғанда), 1-ден 2-ге дейінгі бағандар (қоса алғанда)
submatrix = matrix[1:3, 1:3]
print(f"Ішкі матрица:\n{submatrix}")

Ішкі матрица:
[[ 6  7]
 [10 11]]


### 2.3. Пішінді өзгерту (Reshape) және біріктіру (конкатенация)

Массивтің құрылымын өзгерту немесе бірнеше массивті біріктіру қажеттілігі жиі туындайды.

**Қолданылатын функциялар мен әдістер:**
*   `.reshape()`: Массивтің деректерін өзгертпестен оның пішінін өзгертеді. Элементтердің жалпы саны сақталуы тиіс.
*   `np.vstack()`: Массивтерді тігінен біріктіреді (vertical stack). Массивтер бірінің үстіне бірі қойылады.
*   `np.hstack()`: Массивтерді көлденеңінен біріктіреді (horizontal stack). Массивтер бірінің жанына бірі қойылады.

In [ ]:
arr = np.arange(9)
matrix = arr.reshape(3, 3)
print(f"3x3 матрицасы:\n{matrix}")

3x3 матрицасы:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Элементтер саны сәйкес келмейтін пішінге өзгерту әрекеті қате тудырады
try:
    arr.reshape(4, 4)
except ValueError as e:
    print(f"Қате: {e}")

ValueError: cannot reshape array of size 9 into shape (4,4)

In [ ]:
# np.vstack (vertical stack)
v_stack = np.vstack((matrix, matrix))
print(f"Тігінен біріктіру (vstack):\n{v_stack}")

Тігінен біріктіру (vstack):
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# np.hstack (horizontal stack)
h_stack = np.hstack((matrix, matrix))
print(f"Көлденеңінен біріктіру (hstack):\n{h_stack}")

Көлденеңінен біріктіру (hstack):
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]]


## 3. Массивтермен операциялар

NumPy-дың күші — векторизацияда: операциялар цикл жазуды қажет етпестен, бірден бүкіл массивке қолданылады.

### 3.1. Элемент бойынша операциялар
Стандартты арифметикалық операторлар (`+`, `-`, `*`, `/`, `**`) элемент бойынша жұмыс істейді.

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[10, 20], [30, 40]])
print(f"A + B:\n{A + B}")
print(f"A * B:\n{A * B}")

A + B:
[[11 22]
 [33 44]]
A * B:
[[ 10  40]
 [ 90 160]]


### 3.2. Хабар тарату (Broadcasting)
Broadcasting — бұл NumPy-ға әртүрлі пішіндегі массивтермен операциялар орындауға мүмкіндік беретін механизм. Кіші массив үлкенінің пішініне сәйкес келу үшін "созылады" (жадта нақты көшірме жасамай).

In [ ]:
matrix = np.arange(9).reshape(3, 3)
vector = np.array([10, 20, 30])
print(f"Матрица:\n{matrix}")
print(f"Вектор: {vector}")

# Пішіні (3,) болатын вектор пішіні (3, 3) болатын матрицаға қосылады.
# NumPy векторды әрбір жол үшін көшірілгендей етіп 'созады'.
result = matrix + vector
print(f"Қосу нәтижесі:\n{result}")

Матрица:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Вектор: [10 20 30]
Қосу нәтижесі:
[[10 21 32]
 [13 24 35]
 [16 27 38]]


### 3.3. Матрицалық көбейту
Элемент бойынша көбейтуді (`*`) сызықтық алгебра ережелері бойынша орындалатын матрицалық көбейтумен шатастырмаңыз. Ол үшін үш негізгі тәсіл бар.

**Қолданылатын операторлар мен функциялар:**
*   `@` (оператор): Заманауи және ұсынылатын тәсіл.
*   `np.dot()`: Скалярлық/матрицалық көбейтуге арналған классикалық функция.
*   `.dot()` (әдіс): `ndarray` нысанының өз әдісі.

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[10, 20], [30, 40]])

print(f"1-тәсіл (@):\n{A @ B}\n")
print(f"2-тәсіл (np.dot):\n{np.dot(A, B)}\n")
print(f"3-тәсіл (.dot):\n{A.dot(B)}\n")

1-тәсіл (@):
[[ 70  90]
 [150 200]]
2-тәсіл (np.dot):
[[ 70  90]
 [150 200]]
3-тәсіл (.dot):
[[ 70  90]
 [150 200]]


## 4. Шартты таңдау (Boolean Indexing)

Массивті шарт негізінде сүзуге мүмкіндік береді. Алдымен `True`/`False` мәндерінен тұратын "маска" жасалады, содан кейін ол элементтерді таңдау үшін қолданылады.

In [ ]:
arr = np.arange(11)
print(f"Бастапқы массив: {arr}")

# Буль маскасын жасаймыз
mask = arr > 4
print(f"Шарт (маска) > 4: {mask}")

# Сүзу үшін масканы қолданамыз
print(f"4-тен үлкен элементтер: {arr[mask]}")

# Шарттарды біріктіру: & (логикалық ЖӘНЕ), | (логикалық НЕМЕСЕ)
combined_mask = (arr > 2) & (arr < 8)
print(f"2-ден үлкен ЖӘНЕ 8-ден кіші элементтер: {arr[combined_mask]}")

Бастапқы массив: [ 0  1  2  3  4  5  6  7  8  9 10]
Шарт (маска) > 4: [False False False False False  True  True  True  True  True  True]
4-тен үлкен элементтер: [ 5  6  7  8  9 10]
2-ден үлкен ЖӘНЕ 8-ден кіші элементтер: [3 4 5 6 7]


## 5. Агрегаттаушы функциялар

NumPy массив бойынша статистиканы есептеуге арналған көптеген функцияларды ұсынады. `axis` параметрі негізгі болып табылады.
*   `axis=0`: операция әрбір **бағанның** элементтеріне қолданылады.
*   `axis=1`: операция әрбір **жолдың** элементтеріне қолданылады.

In [ ]:
matrix = np.arange(1, 10).reshape(3, 3)
print(f"Матрица:\n{matrix}\n")

print(f"Барлық элементтердің қосындысы: {matrix.sum()}")
print(f"Бағандар бойынша қосынды (axis=0): {matrix.sum(axis=0)}")
print(f"Жолдар бойынша қосынды (axis=1): {matrix.sum(axis=1)}")
print(f"Бағандар бойынша орташа мән (axis=0): {matrix.mean(axis=0)}")

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Барлық элементтердің қосындысы: 45
Бағандар бойынша қосынды (axis=0): [12 15 18]
Жолдар бойынша қосынды (axis=1): [ 6 15 24]
Бағандар бойынша орташа мән (axis=0): [4. 5. 6.]


## 6. NumPy Машиналық оқытуда

Неліктен біз NumPy-ға сонша көп көңіл бөлеміз? Себебі бұл Python-дағы бүкіл машиналық оқытудың "жұмыс аты".

1.  **Деректерді ұсыну:** Біз жұмыс істейтін кез келген деректер жиынтығы соңында NumPy массиві ретінде ұсынылады. Белгілер матрицасы `X` — бұл 2D массив, мұнда жолдар — нысандар, ал бағандар — белгілер. Мақсатты айнымалы векторы `y` — бұл 1D массив.

2.  **Өнімділік:** Машиналық оқыту алгоритмдері өте көп математикалық операцияларды қамтиды. Оларды Python циклдарында орындау өте баяу болар еді. NumPy-дың векторланған операциялары бұл есептеулерді C немесе Fortran-да жазылған кодпен бірдей жылдамдықта орындауға мүмкіндік береді.

3.  **Математикалық негіз:** Сызықтық алгебра — бұл машиналық оқытудың тілі. Скалярлық көбейту, матрицалық көбейту, кері матрицаларды табу — сызықтық регрессия, негізгі компоненттер әдісі және басқа да көптеген алгоритмдердің негізінде жатқан осы операциялардың барлығы NumPy-да тиімді жүзеге асырылған.

4.  **Экосистемамен интеграция:** Біз әрі қарай қолданатын кітапханалар (Pandas, Scikit-learn) NumPy негізінде құрылған және оның массивтерін деректер алмасудың негізгі форматы ретінде пайдаланады.