# №2 Семинар: NumPy-мен жұмыс істеу тәжірибесі

**Курс:** Машиналық оқыту

### Студент туралы ақпарат

**Аты-жөні:** *<студент бұл жерге өз деректерін жазуы керек>*

**Тобы:** *<студент бұл жерге өз деректерін жазуы керек>*

### Бағалау саясаты

**Жұмыс үшін максималды баға: 6 балл.**

**Семинардың мақсаты:** Дәрісте алынған NumPy кітапханасымен жұмыс істеудің негізгі дағдыларын тәжірибеде бекіту және зертханалық жұмысқа дайындалу.

---

## Қысқаша теориялық анықтама

Тапсырмаларды орындау алдында дәрістің негізгі сәттерін жылдам қайталап өтейік.

### Массивтерді құру
- `np.array(list)`: Python тізімінен массив жасайды.
- `np.arange(start, stop, step)`: Біркелкі қадаммен массив жасайды.
- `np.linspace(start, stop, num)`: `num` санымен бірдей қашықтықта орналасқан нүктелерден тұратын массив жасайды.
- `np.zeros(shape)`: Берілген пішіндегі нөлдерден тұратын массив жасайды.
- `np.ones(shape)`: Бірліктерден тұратын массив жасайды.
- `np.eye(N)`: NxN бірлік матрицасын жасайды.
- `np.random.rand(d0, d1)`: [0, 1) аралығындағы біркелкі үлестірілімнен алынған кездейсоқ сандар массиві.
- `np.random.randn(d0, d1)`: Стандартты қалыпты үлестірілімнен алынған кездейсоқ сандар массиві.
- `np.random.randint(low, high, size)`: Кездейсоқ бүтін сандар массиві.

### Индекстеу және кесінділер
- **Индекстеу** `0`-ден басталады.
- **2D-массив (матрица) үшін синтаксис:** `mat[row, col]`
- **Кесінділер:** `mat[start_row:stop_row, start_col:stop_col]`
  - `:` осы ось бойынша "барлық элементтер" дегенді білдіреді.
  - `stop` кесіндіге кірмейді.

### Агрегаттаушы функциялар және `axis` параметрі
- **Функциялар:** `.sum()`, `.mean()`, `.max()`, `.min()`, `.std()`, `.var()`
- **`axis=0`**: Операция **бағандар бойынша** (жоғарыдан төмен) орындалады.
- **`axis=1`**: Операция **жолдар бойынша** (солдан оңға) орындалады.

---

## Тәжірибелік тапсырмалар

Төменде **қарайтылған** шрифтпен көрсетілген тапсырмаларды орындаңыз.

#### 1. NumPy-ды np ретінде импорттаңыз

In [ ]:
import numpy as np

#### 2. 10 нөлден тұратын массив құрыңыз

In [ ]:
# Осы ұяшыққа шешіміңізді жазыңыз

#### 3. 10 бірліктен тұратын массив құрыңыз

In [ ]:
# Осы ұяшыққа шешіміңізді жазыңыз

#### 4. 10 бестіктен тұратын массив құрыңыз

In [ ]:
# Осы ұяшыққа шешіміңізді жазыңыз

#### 5. 10-нан 50-ге дейінгі бүтін сандардан тұратын массив құрыңыз

In [ ]:
# Осы ұяшыққа шешіміңізді жазыңыз

#### 6. 10-нан 50-ге дейінгі барлық жұп сандардан тұратын массив құрыңыз

In [ ]:
# Осы ұяшыққа шешіміңізді жазыңыз

#### 7. 0-ден 8-ге дейінгі мәндері бар 3x3 матрицасын құрыңыз

In [ ]:
# Осы ұяшыққа шешіміңізді жазыңыз

#### 8. 3x3 өлшемді бірлік матрицасын құрыңыз

In [ ]:
# Осы ұяшыққа шешіміңізді жазыңыз

#### 9. NumPy көмегімен 0-ден 1-ге дейінгі аралықта кездейсоқ сан генерациялаңыз

In [ ]:
# Осы ұяшыққа шешіміңізді жазыңыз

#### 10. NumPy көмегімен стандартты қалыпты үлестірілімнен алынған 25 кездейсоқ саннан тұратын массив генерациялаңыз

In [ ]:
# Осы ұяшыққа шешіміңізді жазыңыз

#### 11. Төменде көрсетілген матрицаны құрыңыз. *Кеңес: деректер типіне назар аударыңыз.*

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ], <br>
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ], <br>
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ], <br>
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ], <br>
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ], <br>
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ], <br>
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ], <br>
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ], <br>
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ], <br>
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
# Осы ұяшыққа шешіміңізді жазыңыз

#### 12. 0 мен 1 арасындағы бір-бірінен бірдей қашықтықта орналасқан 20 нүктеден тұратын массив құрыңыз:

In [ ]:
# Осы ұяшыққа шешіміңізді жазыңыз

## NumPy индекстеуі

Енді сізге матрицадан деректерді шығарып алуды жаттықтыру керек. Ол үшін алдымен `mat` матрицасын жасау үшін келесі ұяшықты іске қосыңыз.

In [ ]:
# ОСЫ ҰЯШЫҚТЫ ІСКЕ ҚОСЫҢЫЗ
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. `mat` матрицасы негізінде төменде көрсетілген матрицаны шығаратын код жазыңыз (кеңес - кесінділерді қолданыңыз).

array( <br>
[[12, 13, 14, 15], <br>
[17, 18, 19, 20], <br>
[22, 23, 24, 25]])

In [ ]:
# Осы ұяшыққа шешіміңізді жазыңыз

#### 14. `mat` матрицасы негізінде 20 санын шығаратын код жазыңыз.

20

In [ ]:
# Осы ұяшыққа шешіміңізді жазыңыз

#### 15. `mat` матрицасы негізінде төменде көрсетілген матрицаны шығаратын код жазыңыз.

array([[ 2], <br>
       [ 7], <br>
       [12]])

In [ ]:
# Осы ұяшыққа шешіміңізді жазыңыз

#### 16. `mat` матрицасы негізінде төменде көрсетілген матрицаны шығаратын код жазыңыз.

array([21, 22, 23, 24, 25])

In [ ]:
# Осы ұяшыққа шешіміңізді жазыңыз

#### 17. `mat` матрицасы негізінде төменде көрсетілген матрицаны шығаратын код жазыңыз.

array([[16, 17, 18, 19, 20], <br>
       [21, 22, 23, 24, 25]])

In [ ]:
# Осы ұяшыққа шешіміңізді жазыңыз

## NumPy операциялары

#### 18. mat матрицасындағы барлық сандардың қосындысын табыңыз

In [ ]:
# Осы ұяшыққа шешіміңізді жазыңыз

#### 19. mat матрицасындағы мәндердің стандартты ауытқуын (standard deviation) табыңыз

In [ ]:
# Осы ұяшыққа шешіміңізді жазыңыз

#### 20. mat матрицасындағы әрбір бағанның қосындысын табыңыз

In [ ]:
# Осы ұяшыққа шешіміңізді жазыңыз